version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: tealinux-postgres
    restart: always
    environment:
      POSTGRES_DB: tealinux
      POSTGRES_USER: tealinux_user
      POSTGRES_PASSWORD: tealinux123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
